name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout source repo
      - uses: actions/checkout@v2
      - name: Configure Python 3 environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.12"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src"